// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcy09bJx4Fz3VH744Wex4evtfiPmI5W50',
    appId: '1:1054540742559:web:c55627884b4b49a77e47aa',
    messagingSenderId: '1054540742559',
    projectId: 'messagemee-appp',
    authDomain: 'messagemee-appp.firebaseapp.com',
    storageBucket: 'messagemee-appp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDucXyd_tdTIYUEh_zHiR7bN1qvyj3mFFc',
    appId: '1:1054540742559:android:d91787ad912090a37e47aa',
    messagingSenderId: '1054540742559',
    projectId: 'messagemee-appp',
    storageBucket: 'messagemee-appp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFYm3HgtlRlWjRdgVoWr1kGC-KGNmYec4',
    appId: '1:1054540742559:ios:6c1775fc69f8a9937e47aa',
    messagingSenderId: '1054540742559',
    projectId: 'messagemee-appp',
    storageBucket: 'messagemee-appp.appspot.com',
    iosBundleId: 'com.example.messagemeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFYm3HgtlRlWjRdgVoWr1kGC-KGNmYec4',
    appId: '1:1054540742559:ios:6c1775fc69f8a9937e47aa',
    messagingSenderId: '1054540742559',
    projectId: 'messagemee-appp',
    storageBucket: 'messagemee-appp.appspot.com',
    iosBundleId: 'com.example.messagemeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcy09bJx4Fz3VH744Wex4evtfiPmI5W50',
    appId: '1:1054540742559:web:df7e48f860bb964b7e47aa',
    messagingSenderId: '1054540742559',
    projectId: 'messagemee-appp',
    authDomain: 'messagemee-appp.firebaseapp.com',
    storageBucket: 'messagemee-appp.appspot.com',
  );
}
